### ISSUE TITLE
addEnd returns incorrect end_col

### ISSUE THREAD

**Issue by Varal7** [GumTreeDiff/pythonparser#1]
The current implementation of `addEnd` returns an incorrect `end_col`. It is based on the `first_non_child` of the node. I can't say I understand what is going on but the result is incorrect. For instance, using webdiff:

![Screen Shot 2019-03-19 at 3 49 50 PM](https://user-images.githubusercontent.com/8019486/54637626-75c98380-4a5f-11e9-83ae-73a6a50b6113.png)

**Comment by jrfaller** [comment]
Hi! I tried to improve pythonparser some time ago. Can you try with the new version? Cheers!

**Comment by Varal7** [comment]
Hi, actually I’ve been using the PR I made in #2, which fixes this.

**Comment by jrfaller** [comment]
Wow awesome! I didn't know there was someone working on this since I do not go very often on pythonparser's repo. I committed the code but I am not the original author. Last commit I made was to make pythonparser compatible with the official GumTree XML exchange format to simplify its integration in GumTree. Along the way I simplified the code a bit and made some fixes. But surely, your version is better than mine, so it would make sense to replace my version by yours. Do you think you could adapt the output to produce a standard GumTree XML? I could help you to show you how it works (for instance it is explained here : https://github.com/GumTreeDiff/gumtree/issues/164).

**Comment by jrfaller** [comment]
Closing this since we now use Parso for parsing.
